Cargo.lock, Cargo.toml, src/ber/de/error.rs, src/ber/de/parser.rs
=> Upgrade nom to 0.6.0-beta1

macros/src/config.rs, macros/src/decode.rs, macros/src/encode.rs, tests/derive.rs
=> Add a new `#[rasn(choice)]` field attribute

src/types/prefix.rs
Fixes  #28, allows access to both Implicit and Explicit value's.
=> Making Implicit and Explicit value's public

standards/cms/src/lib.rs, standards/cms/src/pkcs7_compat.rs
=> Add failing tests.

standards/kerberos/src/lib.rs
fixing misplaced brackets on AsRep and TgsRep tagging
(messed up the other pr https://github.com/XAMPPRocky/rasn/pull/78)
=> fixing tgs/as rep application tag

src/ber/de.rs, src/ber/de/parser.rs
Hey, here is my attempt to fix issue #66.
There were essentially two issues in the code:
* The `decode_any` method wasn't taking indefinite-length contents into account
* The `parse_encoded_value` wasn't implemented correctly for non-primitive types (I think this part wasn't even used anywhere in the code or tests).
I hope it looks ok, I've added a couple of unit tests.
=> Bugfix for indefinite Any parsing, fixes #66

standards/snmp/src/v2.rs
=> Fixes #97 Update SNMP v2 module to better match RFC 3416

src/types/strings/printable.rs
Also small documentation updates, enforce use of `from` or `try_from`, same trait order
=> Add TryFrom for str type for PrintableString

src/ber.rs, src/ber/de.rs, src/ber/enc.rs
Other codecs seems to re-use bytepresentation of BER encoding for ObjectIdentifier type. 
This change would make it easier to access bytes without added length or tags.
=> Split OID codec functionality in BER to be usable by other codecs

.github/workflows/rust.yml, ci/fmt-check.bash, ci/set_rust_version.bash, macros/src/tag.rs, src/de.rs, src/per.rs, src/per/de.rs, standards/pkix/tests/issue141.rs, tests/issue165.rs
Hi :wave: 
I've noticed some `fmt` commits and thought it may be a good idea to just check it on PR time.
I'm happy to hear implementation suggestions :)
Thanks for your time!
=> Add CI check for formatted files and reformat source

src/ber/de.rs, src/per/de.rs, src/types/strings/constrained.rs
Ref https://github.com/XAMPPRocky/rasn/discussions/194
=> Use `ok_or_else` instead of `ok_or` in Error handling for performance

src/ber.rs, src/types.rs
decoding integers encoded with byte lengths greater than `{integer}::BITS / 8` would cause a subtraction underflow and subsequent index panic
=> fix: decoding integers panic

src/lib.rs, src/oer.rs, src/oer/de.rs
=> OER: check quantity data size on sequence of

.github/workflows/rust.yml, src/per/enc.rs, src/types/strings/ia5.rs, src/types/strings/visible.rs, tests/issue286.rs
=> Add integer value constraint checking for PER encoding

src/types/constraints.rs
Small change, but not insignificant!
Function `override_constraints` could be optimized further later on, because it is one of the most used ones.
=> Reduce cloning in constraints

.github/workflows/rust.yml, src/ber/enc.rs, src/error/decode.rs, src/error/encode.rs, src/error/mod.rs, src/jer/de.rs, src/jer/enc.rs, src/per/enc.rs, src/types/tag.rs
Includes also fixes from the beta channel. There were also some unused types in tests.
=> Clippy fixes and CI artifact upload/download update

standards/ldap/src/lib.rs
Fixes #304 
As far as I understand, this was just one line change?
=> Change LDAPString to be UTF-8

.github/workflows/rust.yml, ci/rustdoc.bash, macros/src/decode.rs, src/error/decode.rs, src/error/encode.rs, src/jer/enc.rs, src/types.rs, src/types/constraints.rs, src/types/constructed.rs, standards/cms/src/authenticode.rs, standards/cms/src/lib.rs, standards/kerberos/src/lib.rs, standards/ldap/src/lib.rs, standards/pkix/src/lib.rs, standards/pkix/tests/digicert.rs, standards/snmp/src/v3.rs, standards/snmp/tests/issue153.rs
Fixes #334 , at least I hope so.
=> fix: Run clippy and rustdoc only on stable channel in CI

Cargo.lock, macros/Cargo.toml, macros/src/config.rs, macros/src/encode.rs, macros/src/enum.rs, macros/src/tag.rs, src/ber/de.rs, src/oer/de.rs, src/oer/enc.rs, src/per/de.rs, src/per/enc.rs
=> Update to syn2

.github/workflows/release-plz.yaml
Hopefully makes release-plz work until fixed in the upstream.
=> fix: pin release-plz version until fixed

src/types/constraints.rs
applied clippy's suggestions for the lints, hopefully fixes CI failures
=> fix: some clippy lints causing CI to fail

src/ber.rs, src/ber/de.rs
Fixes #417 
Also might improve performance by reducing allocations.
=> BER: improve GeneralizedTime parsing

README.md
Adds origins for the OER codec.
=> readme: add OER origins

Cargo.toml
My bad of adding too many keywords.
=> Cargo.toml: remove extra keywords

Cargo.lock, Cargo.toml, justfile, src/de.rs, src/per/enc.rs, src/types/strings.rs, src/types/strings/ia5.rs, src/types/strings/octet.rs, src/types/strings/visible.rs, src/uper.rs, standards/kerberos/tests/as_req.rs, standards/snmp/src/v1.rs, standards/snmp/src/v2.rs, tests/strings.rs
Might be of interest to @Nicceboy Locally I got a 10% performance increase in OER and BER.
=> refactor(octet-string): switch from bytes to arc-slice
