Cargo.lock, Cargo.toml, src/ber.rs, src/ber/enc.rs
Addresses #7, adds an `encode_constructed` function to replace `encode_value` when called to encode sequences or sets.
Added test case to confirm this behavior.
All other tests pass.
=> Fix implicitly tagged sequences

README.md
Previously, the docs.rs badge showed the version for `tokei` [![Documentation](https://docs.rs/tokei/badge.svg)](https://docs.rs/rasn/) instead of `rasn` [![Documentation](https://docs.rs/rasn/badge.svg)](https://docs.rs/rasn/) .
=> Fix docs.rs badge

Cargo.toml, src/types/tag.rs
Disabled default feature of konst dependency, since no crate features are used.
=> Changed `slice_range(foo, _, foo.len())` to `slice_from(foo, _)`

macros/src/decode.rs, macros/src/encode.rs
Some small changes to add type information to the error messages about CHOICE enums, to help narrow down the search for issues with deeply-nested data structures.
Also, I noticed the `TAG_n` constant definitions emitted in `derive_enum_impl` are no longer referenced since the match block has been completely eliminated, so I removed them for a small cleanup.
=> Small improvements to error messages, and clean up newly-dead tag constant defs

Cargo.toml, src/types/tag.rs
Disabled default feature of konst dependency, since no crate features are used.
=> Redo: Changed `slice_range(foo, _, foo.len())` to `slice_from(foo, _)`

src/ber/de/parser.rs
* change endianness to big
* change the test to make the first octet nonzero
Fixes https://github.com/XAMPPRocky/rasn/issues/53
=> Fix long form tag decoding

standards/kerberos/src/lib.rs
seems like a few of the tags weren't set as explicit following the macro changes
=> kerberos: fixing a few tags not set as explicit

standards/pkix/src/attribute_certificate.rs, standards/pkix/src/lib.rs, standards/pkix/tests/digicert.rs
Pull request modifies `Attribute`, `RelativeDistinguishedName`  and adds `AttributeTypeAndValue` to match RFCs, as detailed below.
Change `value` to `values`; use `SetOf<AttributeValue>` instead of `AttributeValue`.
Defined in module PKIX1Explicit88 (https://www.itu.int/wftp3/Public/t/fl/ietf/rfc/rfc3280/PKIX1Explicit88.html)
```
Attribute               ::= SEQUENCE {
type             AttributeType,
values    SET OF AttributeValue }
-- at least one value is required
AttributeType           ::= OBJECT IDENTIFIER     
AttributeValue          ::= ANY -- DEFINED BY AttributeType       
```
Also defined in RFC 5652 (https://www.ietf.org/rfc/rfc5652)
```
Attribute ::= SEQUENCE {
attrType OBJECT IDENTIFIER,
attrValues SET OF AttributeValue }
AttributeValue ::= ANY        
```
`Attribute` uses in …
=> Modify Attribute, RelativeDistinguishedName and add AttributeTypeAndValue to match RFCs

macros/src/decode.rs, macros/src/encode.rs, macros/src/enum.rs
The idea here is when using the #[derive()] macros, we don't interfere with libraries that have aliased `Result` to `Result<T, MyError>`.
=> Convert `Result` in macros to `core::result::Result`

standards/pkix/src/attribute_certificate.rs
Just like the Validity structure:
```rust
/// The validity period of the certificate.
#[derive(AsnType, Clone, Copy, Debug, Decode, Encode, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Validity {
pub not_before: Time,
pub not_after: Time,
}
```
I made the AttributeCertificateValidityPeriod fields also pub
```rust
#[derive(AsnType, Clone, Debug, Decode, Encode, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AttributeCertificateValidityPeriod {
pub not_before: GeneralizedTime,
pub not_after: GeneralizedTime,
}
```
=> AttributeCertificateValidityPeriod public fields

compiler/src/codegen.rs, compiler/src/codegen/constant.rs, compiler/src/codegen/constant_enum.rs, compiler/src/codegen/imports.rs, compiler/src/codegen/structs.rs, compiler/src/lib.rs, compiler/src/parser.rs, compiler/src/parser/types/prefix.rs
It can convert this `asn1` schema:
```asn1
Simple DEFINITIONS ::=
BEGIN
SimpleSequence ::= SEQUENCE {
someInt INTEGER,
someBytes OCTET STRING
}
MoreComplexSequence ::= SEQUENCE {
someOptionalInt INTEGER OPTIONAL,
someIntEnum INTEGER {value1(123), value2(456)},
someOptionalBytes OCTET STRING OPTIONAL,
someOptionalReference SimpleSequence OPTIONAL,
someOptionalReferenceWithContextNumber [2] SimpleSequence OPTIONAL,
someAnonymousSequence SEQUENCE {
simpleInt INTEGER
}
}
MainSequence ::= [APPLICATION 1] EXPLICIT SEQUENCE {
simpleSequence SimpleSequence,
moreComplexSequence MoreComplexSequence
}
END
```
To this `Rust` code:
```rust
use rasn::types::OctetString;
use rasn::types::Integer;
use rasn::Encode;
use rasn::Decode;
use rasn::AsnType;
#[non_exhaustive]
pub struct SomeIntEnum;
impl …
```
=> wip: very very basic compiler implementation

src/ber/enc.rs
Fixes #72 
I think this should be sufficient for my use case, however I did have a question. I originally had a `new_set_with_buffer` but as `self.output()` doesn't actually use the `self.output` for the final encoding when `is_set_encoding: true` and is `mem::take(&mut self.output)`'d elsewhere, I felt like it would be pretty useless since the whole point is to allow reusing the buffer space for the final encoding, but this does kind of expose this implementation detail and could cause some confusion since there's a missing function, not entirely sure what a good solution is for this.
Let me know if there's anything else you'd like adjusted.
=> Allow buffer reuse in `Encoder`

standards/pkix/src/lib.rs
Without `explicit`, it returns empty vec for all extensions, and can't parse any existed CRL properly.
e.g. http://crls.pki.goog/gts1c3/zdATt0Ex_Fk.crl
=> Fix tag on PKIX CRL extension

src/types/strings/printable.rs
Great library!
Removed duplicates of 'E' and 'e' characters in the `PrintableString` character set
=> fix: remove duplicates in PrintableString char set

macros/src/config.rs, macros/src/enum.rs, src/per/enc.rs
Fix Clippy warnings on default configuration.
There seems to be also quite many warnings on pedantic level when checking with `﻿﻿cargo clippy -- -W clippy::pedantic` 
Would it be okay to also attempt to fix some of these?
=> Fix Clippy warnings

src/ber/de.rs, src/ber/enc.rs
=> correctly handle non-byte-aligned BIT STRING length

src/per/de.rs
Hey,
I ran the Facebook's MIRAI  static analysis tool for this project, and it identified couple issues which might be real or not.
I added boundary checks for some arithmetics as a result, which looked like potential problem scenarios. I do not understand to code well enough to say for sure. Or should we create tests for these?
Adding overflow check might come with with small performance penalties. So it might be good to look if some are indeed relevant.
=> Draft: Possibly some safer arithmetics

src/types/constraints.rs
A small suggestion for size constraint to make implementation of codes easier.
Makes underlying Bounded object public and adds few functions to detect the type of the Size.
I also added `#[must_use]` attributes, since calling these without using the result does not make sense.
=> Improved size constraint

Cargo.toml, src/ber.rs, src/ber/de.rs, src/ber/enc.rs
BER GeneralizedTime decoder should now handle all cases.
Added stricter function also for CER/DER. 
I am not sure, if we should use BER decoder for CER/DER as well, but at least asn1tools use stricter versions. 
Resolves #57 
Also Encoder produces valid canonical form now.
Make these functions public, so that other codecs can access them.
Since BER allows any ASN.1 compatible GeneralizedTime type, should this check to be moved into the type itself?
=> Improves BER GeneralizedTime decoders, support for CER/DER strict mode

src/ber.rs, src/ber/de.rs, src/ber/enc.rs
Splits functionality similarly than for GeneralizedTime.
Restricted decode for CER/DER.
There was a bug when decoding time offset values, `991231235959+0000` is corresponding value for `991231235959Z` but in tests it was `991231235959+0200`.
=> ber: Split and improve UtcTime encode/decode

macros/src/enum.rs, tests/derive.rs
Fixes an instance where `Result` is used in the proc macros instead of `core::result::Result`. Without scoping, any crate-local types named `Result` confuse the compiler.
=> Fix Result scoping

macros/src/decode.rs, macros/src/encode.rs, tests/derive.rs
So, this one is probably controversial since it likely constitutes a breaking change. This is basically me scratching an itch with #161.
The scenario is explained in the linked issue, basically I want
```
Newtype3(Newtype2(Newtype1(ComplexType)))
```
where each of the `Newtype`s has `#[rasn(delegate)]` set in the derive macro to directly serialize as `ComplexType`. I added some tests with this PR as well.
If this doesn't get accepted I won't be hurt, but I would like to have some kind of way of doing the above because it's becoming very common for me to wrap some none-rasn-serializable value in another library with a `Newtype(SomeForeignType)` and I don't want to have to write a bunch of serialize/deserialize stuff by hand each time.
=> Delegate newtype EOC

macros/src/decode.rs, macros/src/encode.rs, macros/src/enum.rs, tests/derive.rs
Use "gensym" idents when enumerating named fields. instead of raw field names (ie `name`, `tag`, etc), prefix the fields
with `__rasn_field_`: `__rasn_field_name`, `__rasn_field_tag`, etc.
This is so an enum like this can compile (it does not compile without this PR):
```rust
#[derive(AsnType, Decode, Encode)]
#[rasn(choice)]
enum MyEnum {
#[rasn(tag(explicit(0)))]
SomeVariant {
#[rasn(tag(explicit(0)))]
encoder: String,
#[rasn(tag(explicit(1)))]
tag: String,
}
}
```
The idents `encoder` and `tag` conflict with the function args `encoder`/`tag` generated by the derive macro. In other words, it's not possible to have named enum variants of `encoder`, `tag`, or `constraints` because they conflict with the derived function definition.
This fixes things by prefixing the generated variable …
=> Gensym field names

src/de.rs
Adds a default implementation for the missing `decode_default_with_tag_and_constraints`.
A rasn-struct akin to the following would produce an error, because the `Decode` implementation calls a `decode_default_with_tag_and_constraints` method on the `Decoder` trait that did not exist.
```rust
#[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq)]
#[rasn(automatic_tags)]
#[non_exhaustive]
pub struct DefaultTagAndConstraint {
#[rasn(
value("1..=4294967295"),
default = "number_default"
)]
pub number: u32,
}
```
=> fix(de): missing `decode_default_with_tag_and_constraints`

macros/src/enum.rs, src/per.rs, src/per/de.rs, src/per/enc.rs, src/types/strings/constrained.rs
Closes #176 
This PR fixes four small (u)per issues:
* non-negative binary integer slices were padded right instead of left (I refactored #176 into two separate functions for the different padding use cases)
* extensible ENUMERATED without extended variants was treaded like non-extensible ENUMERATED
* contents of CHOICEs with only one option were not encoded
* extended INTEGERs were not encoded correctly
=> Fix: four uper issues

src/per/enc.rs
This PR fixes a couple of issues with PER-encoding extensible string types, such as `BIT STRING`, `OCTET STRING` or `VisibleString`. Before, extensible string types were in some cases encoded with a duplicate extension marker, in some cases with a wrong length determinant.
I also refactored the string encoders so that extension bits are always written using the `encode_extensible_bit` function, and removed some code duplication by having `encode_length` call the `encode_string_length` function, which is largely identical.
=> fix(per): encoding extensible string types

macros/src/config.rs, src/de.rs, src/error/decode.rs, src/error/encode.rs, src/error/mod.rs
Boxed `Kind` type for error variants.
Also some other error improvements.
~~Parser errors from `Incomplete` and `MismatchedTag` does not include backtrace anymore.
Should restore the performance.~~
=> Field_error improved, Boxed error `kind`, explicit naming also for `DecodeErrorKind`

macros/src/enum.rs, src/jer/de.rs, src/jer/enc.rs, src/per/de.rs, src/per/enc.rs, src/types.rs
I double checked `Option<T::EXTENDED_VARIANTS>` for Choice, and it was actually missing. Seems like it was not too bad to add.
=> Add `Option<T::EXTENDED_VARIANTS>` for Choice, clippy cleanup

macros/src/enum.rs, src/aper.rs, src/ber/enc.rs, src/enc.rs, src/jer/enc.rs, src/per/de.rs, src/per/enc.rs, src/uper.rs
Fixes #201 
PER implementation for ObjectIdentifier is now the same than in asn1tools PER and in OER here, it should include only content objects of DER encoding and not the tag or length. 
There are also some wild macros to get tag information for choice before encoding.
=> Fix PER ObjectIdentifier, correct Alignment for Choice index encoding

standards/ocsp/src/lib.rs
Fixes an issue decoding a `BasicOcspResponse`, looks to be because the `version` field's `default` attribute was not being picked up.
Not sure if this was a typo or if there is a compiler that generates this and the issue is from there.
=> Fix issue with decoding of BasicOcspResponse.

macros/src/config.rs, tests/issue217.rs
Closes #217 
`OptionalEnum::is_option_type` did not properly process references to `Option`s. References to `Option` types are present in enum values with named fields. This PR fixes that behavior and adds a test for it.
=> fix(macro): recognize option references

src/ber/enc.rs, src/bits.rs, tests/issue218.rs
Closes #218
SET OF items need to be encoded in ascending order, comparing the encoded values as octet strings. This PR adds the corresponding sorting logic and a test to assure proper sorting.
=> fix(der): sort SET OF items

src/types/oid.rs, tests/issue222.rs
The implementation of PartialEq<[u32]> for ObjectIdentifier did not compare the inner Cow<[u32]> but 'self' with the other [u32]. This triggered an infinite ping pong between Deref::deref and PartialEq::eq.
Closes #222
=> fix(types): stack overflow in ObjectIdentifier PartialEq

Cargo.toml, src/de.rs, src/jer/de.rs, src/per/enc.rs, standards/cap/Cargo.toml, standards/cms/Cargo.toml, standards/cms/src/authenticode.rs, standards/kerberos/Cargo.toml, standards/ldap/Cargo.toml, standards/mib/Cargo.toml, standards/ocsp/Cargo.toml, standards/pkix/Cargo.toml, standards/smi/Cargo.toml, standards/smi/src/object_type.rs, standards/smi/src/v1.rs, standards/smi/src/v2.rs, standards/smime/Cargo.toml, standards/snmp/Cargo.toml, standards/snmp/src/v3.rs
Updated the dependency versions.
=> Manually fix the incompatible versions (a result of v0.13.0 release) and some clippy warnings

src/error/decode.rs, src/jer.rs, src/jer/de.rs, src/jer/enc.rs, src/types.rs
Hey there!
The JER standard (X.697 22. 2021) mandates that JER-encoded ENUMERATED values must be JSON strings instead of integers.
First PR here, so let me know if it can be improved in any way, thanks!
=> fix(jer): ENUMERATED values as strings

Cargo.toml, macros/src/config.rs
This feature can incur a significant performance penalty, and since it's more of a debugging tool, it should be disabled by default.
In my experiments, there was a ~15x perf improvement when decoding OCSP responses with this feature disabled.
Closes #246
=> Remove `backtraces` from `rasn`'s `default` feature

src/oer.rs, src/oer/de.rs
Decoding of enumerated values in OER handled zero padding when it should be strict instead.
=> Fix: oer enumerated decoding handled zero padding when it should not

ci/clippy.bash, src/coer.rs, src/lib.rs, tests/issue222.rs
Maybe it is not bad thing if we run Clippy for all targets.
This also applies suggested fixes for tests.
=> CI: Run Clippy for all targets

benches/common.rs, src/ber/de.rs, src/de.rs, src/error/decode.rs, src/jer/de.rs, src/lib.rs, src/oer/de.rs, src/per/de.rs, src/types.rs
there's some outstanding concerns around behavior, though all of the tests do pass. mainly, with the `wrapping_add` in the PER `parse_integer` method, and with the `as` casts in the integer type `IntegerType` trait impls as well, but it _seems_ to be working assuming the tests cover enough ground. current preliminary benchmarks seem promising (after modifying the `common.rs` file in `main` to include integer benchmarking), though maybe not quite as significant as I had hoped, but I can perform more performance analysis at some point in the future that specifically looks at the integer decoding alone.
my laptop info for this benchmark run:
```
OS: Arch Linux x86_64
Host: Laptop 13 (AMD Ryzen 7040Series) A7
Kernel: 6.9.3-arch1-1
CPU: AMD Ryzen 7 7840U w/ Radeon 780M Graphics (16) @ 5.1 …
```
=> perf: don't heap allocate a BigInt for every integer that is decoded

macros/src/lib.rs, src/ber/de.rs, src/ber/de/parser.rs
the `BigInt`s that are used to parse OIDs are downcasted to `u32`s later on in the code anyway, so now that we have fixed-sized integer parsing that doesn't roundtrip through `BigInt`s, we can just attempt to deserialize them as `u32`s instead of allocating a bunch. this bought me a ~(-72%) benchmark win on parsing an SNMP packet since every varbind value has an associated OID, and got the parse time below `netsnmp`'s PDU decode for my microbenchmark :)
=> perf(ber): don't allocate `2 + N` `BigInt`s when parsing OIDs

Cargo.toml, src/codec.rs, src/error/decode.rs, src/error/encode.rs, src/error/mod.rs, src/lib.rs
Quick attempt to hide JER implementation that is based on `jzon`, which requires `std` - see https://github.com/librasn/rasn/issues/262.
=> Hide `jer` behind feature (implying `std`)

Cargo.toml
One step toward `no_std` compatibility - see https://github.com/librasn/rasn/issues/262#issuecomment-2167887631.
=> Hide `snafu` backtraces behind `std`

src/oer.rs, src/oer/de.rs
Validation was previously done based on the wrong variable.
=> COER: Fix invalid handling of zero padding on length of length

src/error/decode.rs, src/oer.rs, src/oer/de.rs
Adds an error if unused bits on preamble are not zero.
=> OER: decode error when unused preamble bits are not zero

src/oer.rs, src/oer/de.rs
There was a logic bug when parsing zero padding and there was no length.
That was a cause for null string in #272 instead of None. 
But after consulting the standard again, I think zero padding is not allowed even in OER in this case and whole function can be removed. 
Zeros are allowed in long format.
=> OER: fix empty length decoding, no zero padding allowed

src/coer.rs, src/enc.rs
Constraints where not correctly passed in general when encoding optional type.
=> Pass constraints correctly when encoding optional type

src/coer.rs, src/oer/enc.rs
A bit corner case, but fixes encoding of null value in optional extended type. 
I hope that I understood the use of `()` correctly.
The test should represent
```asn
Omitted ::= SEQUENCE { 
a OctetString OPTIONAL,
...,
omitted     NULL OPTIONAL
}
```
=> OER: correctly encode null in option in extensions

src/per/enc.rs, src/uper.rs
Related to the previous PR.
Actually this fixes all cases where encoding values would be empty in extensions, but the extension presence must be still part of the encoding.
=> PER: fix encoding of empty extension values

macros/src/config.rs, src/error/decode.rs
This is fix for a regression introduced in a75b26b, where `extension required but not present` was changed to `extension_present_but_not_required`, which is not the same meaning.
This fix proposes `required_extension_not_present` name to switch back and enforce the error meaning.
=> Fix error name regression introduced in a75b26b

src/enc.rs
The algorithm introduced in 413a39a relies on the value's tag and an index incremented each time a value is processed. 
In sequences with mixed required and optional values, optional values were not set present in the preamble, causing decoding issues, because of calling `encode_none()` instead of `encode_none_with_tag()` in relevant cases.
This pull request fix this, by calling the correct encoding method for Default/Optional types when the value is None.
=> Encoder: call correct method for Default and Optional types when value is None

src/ber/de.rs, src/types.rs
Integer decoding optimization PR added check for leading bytes when decoding Integer type, however this should happen on codec level rather than on type level.
=> Move BER integer leading byte handling to codec level

src/bits.rs, src/jer/enc.rs, src/oer/enc.rs, src/per/de.rs, src/per/enc.rs, src/types/strings/constrained.rs
I wanted to understand what is wrong with `bitslice.to_bitvec().into_vec()` call combination, because our custom functions add some overhead.
It might actually work as intended, see my comment [here.](https://github.com/ferrilab/bitvec/issues/228#issuecomment-2305929792)
For example, the original problem
```rust
assert_eq!(bitvec::bits![u8, Msb0; 1, 1, 0, 0, 0, 1, 1, 1, 0, 1][2..].to_bitvec().into_vec(), vec![29]);
```
This results to correct `BitVec` but the internal memory layout is not unified as result of slicing. Slicing here combines a set of references internally to construct the intended BitSlice (e.g. two first bits are omitted from the first byte). When we use `to_bitvec()`, this  internal layout is carried on, and internal byte alignment is the same, and `into_vec` result might …
=> Remove `to_vec` and `to_left_padded_vec` as unnecessary and reduce allocations

Cargo.toml
With some basic release build optimizations, we can get around 10-20% performance increase.
Maybe it is okay by default?
E.g. that integer bench:
=> Add two custom profiles for benching lto and debugging

Cargo.lock, Cargo.toml, src/oer/enc.rs, src/per/enc.rs, src/types/tag.rs
`BTreeMap` is not the best type for its current use case in `field_bitfied`. 
We could change it to standard `HashMap` as easy improvement, which is very noticeable after the other allocations are optimized. In the future, this could be improved further as it should be possible to know the field count in compile-time and use stack instead.
=> Replace BTreeMap with HashMap in field_bitfield

src/oer/de.rs, src/oer/enc.rs, src/types/fields.rs
Lack of pre-allocations and not using existing buffers created many unnecessary allocations.
This will reduces them a bit.
I trialed several data types for output buffer, and
```rust
output: alloc::borrow::Cow<'a, RefCell<Vec<u8>>>,
```
seems to be best. I tried sharing direct reference of `Vec<u8>` and also `Bytes/BytesMut`. 
Direct reference was too difficult to add since encoder uses itself recursively. `BytesMut` was much slower. Maybe this is okay for a while.
Now the buffer is re-used when possible. e.g. no length calculation requirement afterwards.
Current improvement based on the integer test:
=> Add basic optimizations for allocations in OER

macros/src/config.rs, macros/src/enum.rs, src/aper.rs, src/ber/de.rs, src/ber/enc.rs, src/coer.rs, src/jer/enc.rs, src/lib.rs, src/oer/de.rs, src/oer/enc.rs, src/per.rs, src/per/de.rs, src/per/enc.rs, src/types.rs, src/types/constraints.rs, src/types/integer.rs, src/uper.rs, standards/kerberos/tests/issue111.rs, standards/pkix/tests/digicert.rs, standards/smi/src/v2.rs
Smaller update based on #318 which might be useful anyway already.
* Add ZERO associated constant for `IntegerType`
* Change Constraints::default() to be const
* Change some other constraint-related functions to be constant
* Add `VARIANCE_CONSTRAINT` for choice type - variance can be calculated in compile time
* Add macros to generate constant constraints, like
```rust
const CONSTRAINTS: Constraints = constraints!(value_constraint!(0, 100), size_constraint!(0, 100));
```
=> Constraint utilities, constraint const default, more const functions

macros/src/config.rs, macros/src/decode.rs, macros/src/encode.rs, src/aper.rs
This is in preparation for #317, but is logically separate.
=> Remove option_type

macros/LICENCE-APACHE, macros/LICENCE-MIT
The `rasn-derive` crate doesn't currently include the license texts, which is technically a requirement for MIT. This PR ensures they will be included in the packaged crate.
=> macros: include license texts in the packaged crate

src/types/oid.rs
The first arc is limited to the values 0, 1 and 2, but the doc comment for ObjectIdentifier::new states that an OID is invalid if the first component is greater than 1. (All other instances of such a statement, found mostly around the Oid type, correctly mention 2 as the minimum.)
=> docs: ObjectIdentifier::new: first arc may be 2

Cargo.toml, fuzzing/Cargo.toml
The use of `/` is deprecated, per the Cargo reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Use `OR` operator in Cargo.toml `license` field

src/coer.rs, src/oer/enc.rs, src/per/enc.rs
Workaround until "final proper" solution for sequence/set field presence tracking is identified.
=> Reroll back to BTreeMap

src/coer.rs, src/oer/de.rs, src/oer/enc.rs
There was a bug when decoding large Tag values, and this fixes that.
Also:
* Removes all allocations related to Tag encoding
* It seems to be possible to use current encoder instance rather than creating new one for Choice encoding which should reduce allocation needs on average.
=> OER: Fix tag decoding and optimise choice/tag encoding further

Cargo.lock, Cargo.toml, src/types/constructed.rs, standards/cbr/src/lib.rs, standards/cms/Cargo.toml, standards/cms/tests/test_cms.rs, standards/pkix/src/est.rs, standards/pkix/tests/digicert.rs
Fixes most of the issues related to dependency updates.
Could it be possible to do large changes in branch so that main does not end up into bad state?
`hashbrown` dependency update seems to break encoding of `BitString` type in BER for some standard tests, I don't know why yet. Should we downgrade that for now?
E.g. `cargo test -p rasn-cms --test test_cms test_cms_signed 1> error.log`
shows failures on `BitString` types only.
[error.log](https://github.com/user-attachments/files/17460949/error.log)
=> Fix most issues related to dependency update, except hashbrown version

Cargo.lock, macros/src/config.rs, src/aper.rs, src/ber.rs, src/ber/de.rs, src/ber/de/parser.rs, src/coer.rs, src/de.rs, src/jer/de.rs, src/oer/de.rs, src/oer/enc.rs, src/per/de.rs, src/per/enc.rs
BER currently does not handle the decoding of extended fields correctly.
* If there are no root components in sequence, field decoding is skipped
* Value of the explicit/implict tag is not carried (macros are not generating it for `decode_extension_addition` and function does not have the parameter), so assert of tag value will fail later in 
https://github.com/librasn/rasn/blob/d1208daf6f818226c185ce0d3fb51a23c3708081/src/ber/de/parser.rs#L23-L25
I am not sure if it is possible to fix without major changes or complete removal of the assert, so I just changed assert to apply for non-universal tags.
Maybe cargo.lock update fixes the main as well?
=> BER: fix decoding of extended fields in sequence

macros/src/config.rs, macros/src/decode.rs
Also fix an oversight from the syn2 migration that wasn't caught in the testcases.
=> Disallow structs without fields for a `set`

benches/criterion.rs, macros/src/ext.rs, tests/generics.rs
Fixes https://github.com/librasn/rasn/issues/193
=> fix: Don't override generics impl in proc-macros on encode impl

Cargo.toml, benches/criterion.rs
Maybe it is okay to assume that x509 benches are only needed on `aarch64` and `x86_64`.
=> bench: run x509 benches only on x86_64 or aarch64

benches/integer.rs
Wraps the integer bench cases with `black_box` method to possibly prevent some compiler optimizations which are not realistic.
=> bench: use black box on integer test, change for macros

Cargo.lock, Cargo.toml, benches/iai.rs
This requires the iai-callgrind-runner binary to be installed (possible via cargo install), but has the advantage of working with a recent valgrind version (iai seems to be unmaintained for the past years).
=> Update from iai to iai-callgrind

.github/workflows/release-plz.yaml
Maybe the latest version works now. (https://github.com/MarcoIeni/release-plz/issues/1791#issuecomment-2440815911)
=> fix: remove version pin from release-plz

.github/workflows/base_benchmarks.yml
This should install valgrind, which iai and iai-callgrind need to run.
=> Attempt to fix base benchmarks on CI

.github/workflows/base_benchmarks.yml, Cargo.toml
One attempt more to see if benches work. After there is some historical data, we can change this to apply all PRs?
=> fix: split iai and criterion benches, use correct adapters

Cargo.lock, Cargo.toml
Fixes #359
As discussed in that issue, removes rayon from the dependencies, making the crate a little more lightweight to install.
=> Remove dependency on rayon

standards/ldap/src/lib.rs
I think I found the solution to my own issue. It seems the newly introduced type LdapString did not properly define its ASN tag. I can confirm that my issue #368 goes away with this change. But this definitely needs review from someone with more insight into ASN and rasn.
closes #368
=> fix(ldap): correct tag handing in Decoder and Encoder impls for LdapString

macros/macros_impl/src/decode.rs, src/oer/de.rs
Similar than #324 but for decoding, and OER only for now.
Also fixes casing in one pro-macro variable.
Extended integer test:
=> OER: improve decoding field presence tracking

src/coer.rs, src/oer.rs, src/oer/de.rs
Apparetly using `nom_bitvec` for parsing the input in OER was significantly slower, at least on my usage.
This changes OER to parse `&[u8]` in general.
=> OER: no more BitSlice for general parsing

src/types/integer.rs
Adds some magic to construct integer types directly instead of copying. 
This is visible in on some larger types when mixed with constraints. Regardless of the size of the type, we iterate only the amount of input bytes and construct the type.
=> perf: use shifting to construct primitive integers

src/oer/de.rs, src/oer/enc.rs
Cleans up the rest of the non-mandatory BitSlice/BitView usage.
=> OER: Remove trails of BitSlice and unnecessary length checks

macros/macros_impl/src/config.rs, macros/macros_impl/src/decode.rs, macros/macros_impl/src/encode.rs, src/ber/de.rs, src/jer/enc.rs, src/oer/de.rs, src/per/de.rs, src/per/enc.rs, src/types.rs, standards/cdt/src/lib.rs, standards/mib/src/lib.rs
OER decoding has simplified a bit and we can actually just remove `nom` usage completely.
This improves error messages slightly as well at the same time, and move some historical constants.
=> OER: remove nom usage, improve errors

src/types/strings/bit.rs, tests/strings.rs
PartiallyFixes #383
I am not sure if the current way is the most convenient way to use the type, but without wrapping it with newtype, I will not get much better.
=> fix: FixedBitString might work as expected

src/coer.rs, src/oer.rs, src/oer/de.rs
Currently decoding a stream is a bit cumbersome. Since we pass slices as reference, we don't consume the data. 
Maybe we can have a high level `decode_with_remainder` function that returns the type and reference to the remaining slice. Similar approach should work for other codecs too.
=> OER: Add `decode_with_remainder` for decoding stream

src/error/decode.rs, src/oer/de.rs
Use of format! in error message seemed to introduce allocation regardless whether error happened or not, and it was also in lazily evaluated context, so this is a bit odd.
Allocation does not happen if it is defined in snafu(display())
We likely need to measure impact of every error message then at some point...  
I changed the error for OER in one place since it is in critical place.
=> perf: oer: format! in error messages causes allocation

src/jer/de.rs, tests/strings.rs
If the OctetString isn't of even length in the JSON file, the decoder panics with an index out of bounds error.
This PR introduces a bounds check, such that the index access `octet_string[i..=i + 1]` on line 613 doesn't panic on malformed input. Sample octet string triggering this panic: `"!"`.
=> Fix panic in the JER OctetString decoder if the string isn't even length

src/types/integer.rs
noticed the broken formatting while browsing the docs, this also adds a doc link to `isize` for convenience.
=> docs: fix accidental double backtick in `Integer` docs

src/de.rs
this seems like an accidental holdover from an earlier iteration of the impl or something since there's no need for `T: Default` with the current implementation
=> fix: remove `Default` bound from `[T; N]`'s `Decode` impl

src/types/strings/octet.rs
=> fix: add missing `Copy` impl to `FixedOctetString<N>`

macros/macros_impl/src/asn_type.rs, macros/macros_impl/src/enum.rs, tests/derive.rs
fixes #397. this commit ensures that the `TAG_TREE` associated const uses a `const` block so it is able to access any outer generics on the enum and also bounds any type generics with `AsnType` so that impls will be met.
=> fix(derive): use `const` blocks and add generic bounds when generating an enum's `AsnType` impl

src/macros.rs
this is something I had whipped up for one of my own projects a while back, so figured it might be useful to have in `rasn` proper. there is one caveat with the way this is currently implemented, when an error does occur, the error message is pretty brutal (in that it's filled with a lot of useless `note`s, but I made an issue on the Rust repo about this, so it should get fixed at some point, as it looks like a regression even: https://github.com/rust-lang/rust/issues/135259).
let me know if there's any adjustments or fixes desired for the impl.
=> feat: add a convenience macro for parsing string literals into `&'static Oid`s

Cargo.toml, src/ber/de.rs, src/ber/enc.rs, src/de.rs, src/enc.rs, src/error/decode.rs, src/error/encode.rs, src/jer.rs, src/jer/de.rs, src/jer/enc.rs, src/oer.rs, src/oer/de.rs, src/oer/enc.rs, src/per/de.rs, src/per/enc.rs, src/types.rs, src/types/real.rs
I think this is a compliant implementation of REAL, as long as you're fine with being constrained to 32/64-bit floats.
From what I can gather this is the first type that isn't supported for every codec so I added a generic error for the unsupported codecs. Unfortunately this means that you won't get an error until runtime.
I added f32/f64 feature flags so you don't have to use any of it if you don't want it.
Neither my rust nor my asn.1 is something to brag about, so if you want it done in another way just let me know.
=> Add basic support for REAL using f32/f64 with JER/OER rules

macros/macros_impl/src/config.rs, src/enc.rs, tests/explicit.rs
Currently, when using an explicit tag default values are not considered and only a code path of adding that value to the encoded output is followed.
This change adds support to check if the default value matches and, if so, does not encode it. This will have no impact on the decode path.
=> Fixes librasn/rasn#418. Add support for explict tags and default values to encode correctly

src/aper.rs, src/coer.rs, src/types/integer.rs, src/uper.rs
Fixes #399 
Additionally changes inner type of `ConstrainedInteger` to `i128` since it does not currently make much sense to use `Integer` here.
=> ConstrainedInteger: From -> TryFrom

src/error/decode.rs
Currently, the `UnexpectedEmptyInput` error prints out the following message:
```
SEQUENCE has at least one required field, but no input provided
```
However, not all instances of this error are within SEQUENCE types; some may occur within INTEGER types as well:
https://github.com/librasn/rasn/blob/3e8e3a26048c229b32a66a48362ea476a2ddd92d/src/types/integer.rs#L519-L527
https://github.com/librasn/rasn/blob/3e8e3a26048c229b32a66a48362ea476a2ddd92d/src/types/integer.rs#L637-L645
https://github.com/librasn/rasn/blob/3e8e3a26048c229b32a66a48362ea476a2ddd92d/src/types/integer.rs#L730-L743
(the unexpected_empty_input() function maps to the UnexpectedEmptyInput error):
https://github.com/librasn/rasn/blob/3e8e3a26048c229b32a66a48362ea476a2ddd92d/src/error/decode.rs#L348
This PR simply changes the …
=> Clarify error message for UnexpectedEmptyInput

macros/macros_impl/src/config.rs, macros/macros_impl/src/decode.rs, macros/src/lib.rs, tests/generics.rs
Continues #433 .. Sometimes it can be useful to support newtype pattern and delegate with more than one field when other fields are `PhantomData` type. This allows the use of generics to apply inner constraints for the underlying type.
=> feat: support multi-field tuple-structs with delegate if other types are PhantomData

src/error.rs, src/error/components.rs, src/error/decode.rs, src/types.rs, src/types/constraints.rs
Adds `InnerSubtypeConstraint` constraint trait and some relevant error messages. Mainly used in #389 
Usage requires implementing single method which should validate the inner constraints:
```rust
/// Validates the inner subtype constraints and attempts to decode internal ASN.1 `CONTAINING` constraints as a marked type.
/// Usually this means that some field has `OPAQUE` data, and we need to decode it further as a specific type, as defined in the inner subtype constraint.
/// Manual implementation of this function is required for all types that have inner subtype constraints.
/// # Arguments
/// * `decode_containing_with` - the codec to validate and decode the containing data with - ASN.1 type definiton has `CONTAINING.
fn validate_and_decode_containing(
self,
decode_containing_with: …
```
=> feat: inner subtype constraint

Cargo.lock, Cargo.toml, src/types/constructed.rs
Okay, I am not sure what I was originally thinking, but we can just use `Vec<T>` internally here with `SetOf` and drop the `hashbrown` dependency.
It takes more space internally and equal check is significantly slower but it is likely reasonable trade-off. Not a common type in modern standards. 
Fixes #350
=> fix: remove SetOf hashbrown dependency

Cargo.lock, macros/macros_impl/src/asn_type.rs, macros/macros_impl/src/decode.rs, macros/macros_impl/src/encode.rs, src/coer.rs, src/types/constraints.rs, standards/pkix/src/lib.rs
We did not cover all the intersection combinations for value/size constraints. This adds them with tests.
I was also able to move constraint intersection in delegate context into different place and now those constraints are completely evaluated in compile-time. Around 15% performance boost at least for IEEE 1609.2 certs.
=> fix: improve constraint performance and bounded intersection

Cargo.lock, Cargo.toml
Closes #445
Updates `xml-no-std` to `v0.8.26`, which adopted a fix by kornelski for a decoding panic.
=> chore(xer): update xml-no-std

standards/cms/src/tsp.rs
Contributed under SPDX "MIT OR Apache-2.0" licenses.
Mapping PKIStatus to an enum didn't work out as expected in https://github.com/librasn/rasn/pull/451 when doing interoperability tests:
```text
"Error while decoding data. kind: 'FieldError { name: \"TimeStampResp.status\", nested: DecodeError { kind: FieldError { name: \"PkiStatusInfo.status\", nested: DecodeError { kind: CodecSpecific { inner: Ber(MismatchedTag { expected: Tag { class: Universal, value: 10 }, actual: Tag { class: Universal, value: 2 } }) }, codec: Ber } }, codec: Der } }', codec: 'Der'"
```
Revert to using the one-to-one mapping from [RFC 3161 2.4.2](https://www.rfc-editor.org/rfc/rfc3161#section-2.4.2) :
```text
PKIStatus ::= INTEGER {
...
```
=> Fix invalid mapping of PKIStatus in TSP. 

src/uper.rs
Returns a single zero-octet for empty outermost encodings.
11.1.3.1	(The result of the encoding is not contained in an ASN.1 bitstring) If the result of encoding the outermost value is an empty bit string, the bit string shall be replaced with a single octet with all bits set to 0. If it is a non-empty bit string and it is not a multiple of eight bits, (one to seven) zero bits shall be appended to it to produce a multiple of eight bits.
Technically, there's also the following paragraph to consider, but given that we `rasn::uper::encode` always returns a byte vector that may be padded it does not apply.
11.1.3.2	(The result of the encoding is contained in an ASN.1 bitstring) If the result of encoding the outermost value is an empty bit string, the bit string shall be replaced with a single …
=> fix(uper): empty outer encoding

.github/workflows/rust.yml, src/jer/de.rs, src/oer/enc.rs, src/per/de.rs, src/per/enc.rs, src/types/strings/constrained.rs
It might be possible that `rust-toolchain` file has prevented us from actually running nightly builds and we haven't seen many issues because of that. PR attempts to allow nightly builds to fail without failing the whole pipeline. Also fixes some nightly lint issues.
=> CI: allow nightly workflows to fail
